environment:
  matrix:
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37-x64"
install:
  - "%PYTHON%\\python.exe -m pip install --upgrade pip"
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
build_script:
  - "%PYTHON%\\python.exe -m pip install --verbose ."
test_script:
  - "%PYTHON%\\python.exe -m twisted.trial comet"
